#spring 基础配置文件，dev 表示开发环境， test 表示测试环境， product 表示生产环境
server:
  port: 80
  session:
    timeout: PT2H
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://8.142.98.188:3306/msc?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: liu7485213.
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  cache:
    type: redis
redis:
  session:
    database: 0
  cache:
    database: 0
  host: 127.0.0.1
  port: 6379
#  password:
  password: 7485213
  jedis:
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 0
  timeout: 1000
  client-name: redisClient
  lettuce:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 4
      min-idle: 0
    shutdown-timeout: 4000
mybatis-plus:
  type-aliases-package: com.msc.user.entity
  mapper-locations: classpath:mapper/*.xml
file:
  alicloud:
    bucket-name: msc-oss #上传空间bucket
    access-key: LTAI5tFt88sX1Fww6zUexRti #你的key
    secret-key: vgcspbsRcp05YI4iIvmNcCUhNXisH1 #你的秘钥
    endpoint: oss-cn-hangzhou.aliyuncs.com  #上传端点
  multipart:
    maxFileSize: 20480000
    maxRequestSize: 30000000



